### ISSUE TITLE
[FEATURE] add jsdoc, as a way to document

### ISSUE THREAD

**Issue by buttercubz** [nestdotland/eggs#10]
i think you can add jsdoc for comments and document the cli in general.

**Comment by SteelAlloy** [comment]
We haven't done it everywhere but we will continue to document the code 

For example on this file, what would you like to add?
https://doc.deno.land/https/raw.githubusercontent.com/nestdotland/nest.land/master/eggs-update-handler/lib/registries.ts

**Comment by notfilippo** [comment]
I 💯 agree.  I am going to start adding comments in the `clean-code` branch

**Comment by zorbyte** [comment]
For the most part, typescript documents code quite well and against redundant JSDoc, silky things like @interface when something clearly uses the interface keyword. Other than that, I don't think it's half bad. But we should also consider if it's really necessary, since we're not going to be using docgen features AFAIK.

**Comment by zorbyte** [comment]
Essentially, no JSDoc just yet.

**Comment by SteelAlloy** [comment]
We have documented most of the code. Currently, doc.deno.land is sufficient for our needs.
I'm closing this issue because jsdoc is not planned.
