### ISSUE TITLE
[Question] `eggs update -g` flag missing

### ISSUE THREAD

**Issue by tranzystorekk** [nestdotland/eggs#117]
The `-g` flag that was used to update global installations seems to be gone. Could you clarify why that happened?

Also, the feature is still documented in README and hatcher still hints at doing `eggs update -g` when there is a new version available.

**Comment by SteelAlloy** [comment]
Hi @tranzystorek-io 
The `-g` flag was indeed used to update global installations, but this had a few drawbacks.

Due to the nature of Deno, it is difficult to guess the structure of a project and how it evolves.
That's why we decided to hand over this work to the module authors, letting `eggs` update the modules often brought more problems than it solved.
The code was migrated from `eggs` to `hatcher` and some changes were made.

If an author decides to add `hatcher` to his module, then it is his responsibility to give the command to be executed to update the module. If a user installs a module with `hatcher`, now there is no command to run, the user is prompted to check the command when notified of an update.


> Also, the feature is still documented in README and hatcher still hints at doing `eggs update -g` when there is a new version available.

Thanks for noticing this, the readme will be fixed.

`eggs` is still unstable and subject to changes, but the [stable version](https://github.com/nestdotland/nest) is mostly ready.

**Comment by tranzystorekk** [comment]
I see. It's a shame since I've been looking forward to using `nest.land` and `eggs` as a "one source of truth" package management solution for deno.

Thank you for taking your time to write a detailed explanation anyway! 😄
