### ISSUE TITLE
Deno removed plugin support which breaks the cli completely

### ISSUE THREAD

**Issue by zabihexes** [nestdotland/eggs#130]
![image](https://user-images.githubusercontent.com/83710104/129341499-7bdff6f8-71b8-4fb4-a730-dee46a5cc3a9.png)
(This is with any cli usage.)

**Comment by maximousblk** [comment]
what was the full command you entered? eggs version, deno version?

can you try reinstalling `eggs`?
```sh
deno install -Af --unstable https://x.nest.land/eggs@0.3.8/eggs.ts
```

**Comment by zabihexes** [comment]
Literally try **any** cmd using eggs with Deno `1.13`.
![image](https://user-images.githubusercontent.com/83710104/129353209-5335289e-dca5-4f3a-b8c8-c590aa06eccd.png)

**Comment by zabihexes** [comment]
It works correctly if I downgrade deno back to `1.12`.
![image](https://user-images.githubusercontent.com/83710104/129353560-bfd82c1b-cb10-478e-b58d-a607237587fb.png)

**Comment by maximousblk** [comment]
I'm sorry but that's not helpful at all. did you try reinstalling eggs?

it works fine for me on deno 1.13

![image](https://user-images.githubusercontent.com/28438021/129353616-6749d5f4-e239-4f2d-a0f9-d75062577ef2.png)

**Comment by zabihexes** [comment]
Reinstalling it fixed it for some reason. Any idea why? Thanks. Sorry.

**Comment by maximousblk** [comment]
This is because deno doesn't install the cli with `--allow-all`. It explicitly stores every permission separately. so if you installed eggs in deno 1.12 and then upgraded to 1.13, the installed cli still has the `--allow-plugin` permission

![image](https://user-images.githubusercontent.com/28438021/129354440-7a91ea36-4a8e-4bd2-81a2-8f4814f49a82.png)
