### ISSUE TITLE
[FEATURE] Upload all files if the files field is empty

### ISSUE THREAD

**Issue by martonlederer** [nestdotland/eggs#26]
**Is your feature request related to a problem? If so, please describe.**
A lot of developers are having problems with the files field. They just want to upload all of their files

**Describe the solution you'd like**
If the files field is empty or does not exist, upload all files in the folder

**Comment by t8** [comment]
This could prove beneficial, but it could also prove catastrophic for certain things. I think that if we were to roll this out, we'd need to implement `.eggignore` files first. For example, we **never** want a user's `.git` folder being pushed to Arweave. We also want to avoid environment files.

**Comment by martonlederer** [comment]
I agree. Maybe we implement a check for the git folder and a confirmation message, that all files will be published?

Edit: nevermind, this confirmation thing would be an overkill. `.eggignore` is needed, I'll probably implement it tomorrow

**Comment by t8** [comment]
Haha yes. This will require a bit more deliberation, so let's not start on that yet. Let's discuss this in our meeting tomorrow.

**Comment by notfilippo** [comment]
I think if no .eggignore file nor `files` field is present we should show just an error. I have this opinion only because as it stands now the `publish` command does not ask for confirm and uploads directly (if no --dry flag is explicitly provided). If we plan on showing a (Y/n) prompt on every publish this change could actually be pretty useful for people that don't need / want to declare files.
