### ISSUE TITLE
possible error when updating using deno 1.4

### ISSUE THREAD

**Issue by buttercubz** [nestdotland/eggs#73]
see [denoland/deno#7455](https://github.com/denoland/deno/issues/7455)

**Comment by SteelAlloy** [comment]
This is what I get when installing eggs@0.2.2

Windows
![image](https://user-images.githubusercontent.com/52361520/93228490-d3827d00-f775-11ea-9bf0-d0f5b588a877.png)

Linux (WSL)
![image](https://user-images.githubusercontent.com/52361520/93228510-da10f480-f775-11ea-9743-7d1771c25e99.png)

No error is displayed but nothing happens

**Comment by buttercubz** [comment]
> No error is displayed but nothing happens

that's the mistake

**Comment by yoshixmk** [comment]
Me too.   
Run eggs using Deno 1.4, failed after show "success message".
```
[INFO] Successfully updated .nest-api-key with your key!
[INFO] Formatted your code.
[ERR] deno test returned a non-zero code.
##[error]Process completed with exit code 1.
```
https://github.com/yoshixmk/deno-x-ranking/runs/1128839330?check_suite_focus=true

So, I avoided it by using it in 1.3.3.

**Comment by SteelAlloy** [comment]
@yoshixmk Your problem is different 😉
Eggs doesn't work for deno 1.4 only if it's installed. By running it with `run` (which is done in the github action), there is no bug. Your error comes from the fact that the tests you configured didn't pass for your module with Deno 1.4.
By default, eggs runs `deno test` before releasing to make sure the module is not broken. You can disable this behavior with the option `--check-all=false` or `--no-check-all` or by modifying your egg.json file.

**Comment by yoshixmk** [comment]
@oganexon Thank you for getting in touch with me.

It's hard to believe, but it happened after I [commited to change the version](https://github.com/yoshixmk/deno-x-ranking/commit/ae7b42e31011bc20a6538379afc4a2686fc4f552), so I misunderstood it was a related issue.

**Comment by mjrlowe** [comment]
This was fixed in Deno 1.4.1! You may need to reinstall eggs after updating Deno, but it seems to work now.

**Comment by SteelAlloy** [comment]
Awesome 🚀 
I'll test this later in the day

**Comment by SteelAlloy** [comment]
Fixed 🎉
